# Generated by Django 2.1.3 on 2019-01-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpringService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(max_length=16)),
                ('response_id', models.IntegerField(blank=True)),
                ('response_quote', models.TextField(default='')),
            ],
        ),
    ]
