# Generated by Django 2.1.3 on 2019-01-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='springservice',
            name='response_quote',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='springservice',
            name='response_type',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
