# Generated by Django 2.1.3 on 2018-11-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=64)),
                ('active', models.BooleanField()),
                ('create_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'artist_group',
            },
        ),
    ]
