# Generated by Django 2.1.3 on 2018-11-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20181109_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='album',
            name='publish_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
